// src/utils/mock-data.ts

import { 
  RiskProblemItem, 
  NaturezaEnum, 
  SeveridadeEnum, 
  StatusRiscoEnum,
  StatusProblemaEnum 
} from "@/types/risk-problem";

/**
 * DADOS MOCK - Para testes e desenvolvimento
 * Simula dados que viriam da API
 * 
 * Quando conectar com a API real, delete este arquivo
 */

export const MOCK_RISK_PROBLEM_ITEMS: RiskProblemItem[] = [
  {
    id: "item-001",
    projeto_id: 1,
    tipo_inicial: NaturezaEnum.RISCO,
    natureza_atual: NaturezaEnum.RISCO,
    titulo: "Retomada ao projeto em atraso",
    descricao:
      "O projeto está atrasado em 2 semanas devido a problemas de infraestrutura. Necessário realocação de recursos.",
    origem: "Reunião de Status",
    probabilidade: 4,
    impacto_potencial: 5,
    efetividade_controle: 2,
    nivel_risco_inerente: 20,
    nivel_risco_residual: 10,
    severidade: SeveridadeEnum.CRITICA,
    acao_corretiva: "Aumentar equipe de desenvolvimento em 3 pessoas",
    agente_solucao: "Shirlene",
    data_alvo_solucao: "2026-04-15",
    coordenador_agente: "Andreia",
    status_operacional: StatusRiscoEnum.EM_TRATAMENTO,
    data_status: "2026-03-20T10:30:00Z",
    //atraso_dias: 5,
    criado_em: "2026-03-15T09:00:00Z",
    criado_por: "Pedro",
    atualizado_em: "2026-03-20T10:30:00Z",
    atualizado_por: "Shirlene",
    tags: ["crítico", "infraestrutura", "recursos"],
    observacoes: "Aguardando aprovação do orçamento para contratação",
  },

  {
    id: "item-002",
    projeto_id: 1,
    tipo_inicial: NaturezaEnum.RISCO,
    natureza_atual: NaturezaEnum.PROBLEMA,
    titulo: "Falha na integração com API externa",
    descricao:
      "A API de pagamento está retornando erros 500 em 15% das transações. Impacto direto na conversão.",
    origem: "Jira",
    urgencia: 5,
    impacto_atual: 4,
    prioridade: 20,
    severidade: SeveridadeEnum.CRITICA,
    acao_corretiva: "Contato com suporte da API + implementação de retry logic",
    agente_solucao: "João Silva",
    data_alvo_solucao: "2026-03-22",
    coordenador_agente: "Carlos",
    status_operacional: StatusRiscoEnum.EM_TRATAMENTO,
    data_status: "2026-03-19T14:00:00Z",
    //atraso_dias: 0,
    criado_em: "2026-03-18T08:00:00Z",
    criado_por: "Pedro",
    atualizado_em: "2026-03-20T11:00:00Z",
    atualizado_por: "João Silva",
    convertido_em_problema_em: "2026-03-19T14:00:00Z",
    tags: ["crítico", "pagamento", "api"],
    observacoes: "Suporte respondeu, aguardando patch",
  },

  {
    id: "item-003",
    projeto_id: 1,
    tipo_inicial: NaturezaEnum.RISCO,
    natureza_atual: NaturezaEnum.RISCO,
    titulo: "Falta de documentação técnica",
    descricao:
      "Documentação do projeto está incompleta. Dificulta onboarding de novos desenvolvedores.",
    origem: "Análise Interna",
    probabilidade: 3,
    impacto_potencial: 3,
    efetividade_controle: 4,
    nivel_risco_inerente: 9,
    nivel_risco_residual: 2,
    severidade: SeveridadeEnum.MEDIA,
    acao_corretiva: "Criar documentação técnica completa (README, API docs, arquitetura)",
    agente_solucao: "Maria",
    data_alvo_solucao: "2026-05-01",
    coordenador_agente: "Pedro",
    status_operacional: StatusRiscoEnum.IDENTIFICADO,
    data_status: "2026-03-20T09:00:00Z",
    //atraso_dias: 0,
    criado_em: "2026-03-10T10:00:00Z",
    criado_por: "Pedro",
    atualizado_em: "2026-03-20T09:00:00Z",
    atualizado_por: "Pedro",
    tags: ["documentação", "onboarding"],
    observacoes: "Planejado para sprint 5",
  },

  {
    id: "item-004",
    projeto_id: 1,
    tipo_inicial: NaturezaEnum.PROBLEMA,
    natureza_atual: NaturezaEnum.PROBLEMA,
    titulo: "Performance lenta em mobile",
    descricao:
      "Aplicação está lenta em dispositivos mobile (LCP > 3s). Impacta experiência do usuário.",
    origem: "Lighthouse",
    urgencia: 4,
    impacto_atual: 4,
    prioridade: 16,
    severidade: SeveridadeEnum.ALTA,
    acao_corretiva: "Otimizar imagens, implementar lazy loading, code splitting",
    agente_solucao: "Dev Front-end",
    data_alvo_solucao: "2026-04-10",
    coordenador_agente: "Tech Lead",
    status_operacional: StatusRiscoEnum.EM_TRATAMENTO,
    data_status: "2026-03-18T15:00:00Z",
    //atraso_dias: 2,
    criado_em: "2026-03-08T11:00:00Z",
    criado_por: "Pedro",
    atualizado_em: "2026-03-20T10:00:00Z",
    atualizado_por: "Dev Front-end",
    tags: ["performance", "mobile", "web-vitals"],
    observacoes: "Medições com Lighthouse já feitas",
  },

  {
    id: "item-005",
    projeto_id: 1,
    tipo_inicial: NaturezaEnum.RISCO,
    natureza_atual: NaturezaEnum.RISCO,
    titulo: "Segurança: Validação de entrada insuficiente",
    descricao:
      "Alguns campos de formulário não validam entrada do usuário. Risco de SQL injection e XSS.",
    origem: "Análise de Segurança",
    probabilidade: 2,
    impacto_potencial: 5,
    efetividade_controle: 1,
    nivel_risco_inerente: 10,
    nivel_risco_residual: 10,
    severidade: SeveridadeEnum.CRITICA,
    acao_corretiva: "Implementar validação robusta com Zod/Yup em todos os formulários",
    agente_solucao: "Security Team",
    data_alvo_solucao: "2026-03-31",
    coordenador_agente: "CISO",
    status_operacional: StatusRiscoEnum.EM_TRATAMENTO,
    data_status: "2026-03-17T13:00:00Z",
    //atraso_dias: 0,
    criado_em: "2026-03-05T09:00:00Z",
    criado_por: "Pedro",
    atualizado_em: "2026-03-20T08:00:00Z",
    atualizado_por: "Security Team",
    tags: ["segurança", "crítico", "validação"],
    observacoes: "Bloqueador para produção",
  },
];